export const commands = [
  {
    name: 'help',
    description: 'Shows available commands',
    response: [
      'Available commands:',
      'about       - Learn about me',
      'projects    - View my projects',
      'skills      - See my technical skills',
      'experience  - My work experience',
      'contact     - How to reach me',
      'education   - My educational background',
      'certifications - View my certifications',
      'leadership  - Leadership and community involvement',
      'clear       - Clear the terminal',
      '',
      'Type any command to continue...',
    ],
  },
  {
    name: 'about',
    description: 'Information about me',
    response: [
      '👋 Hello, I\'m Mark Gatere!',
      '',
      'I\'m a Software Engineer with expertise in full-stack development, AI integration, and cloud infrastructure.',
      '',
      'Background:',
      '- Currently a Software Engineering Intern at Microsoft working with the Windows Team',
      '- Previously led the development of payment portals and dashboards at FarCas Consult (FCL)',
      '- Previously worked at Microsoft Garage, Digitalfarmer, and QuizardHQ',
      '- Focus on building scalable web applications and data visualization tools',
      '- Skilled in Next.js, React, AWS, Azure, and AI integration',
      '- Winner of the Ayute Africa Challenge with the Afyamavuno (Agrika) project',
      '',
      'When not coding, I enjoy speaking at tech conferences and contributing to developer communities like GDG and Microsoft Learn.',
      '',
      'Feel free to explore more using the \'projects\', \'skills\', or \'contact\' commands!',
    ],
  },
  {
    name: 'projects',
    description: 'My projects',
    response: [
      '🚀 Projects:',
      '',
      '1. Afyamavuno (Agrika)',
      '   AI platform to detect crop diseases from plant images',
      '   Technologies: Next.js, TypeScript, Python, Flask, TensorFlow, OpenAI API',
      '   Link: https://agrika-ai.vercel.app',
      '',
      '2. Masomo Net',
      '   Subscription-based e-learning platform for students',
      '   Technologies: Next.js, Tailwind CSS, AWS, Supabase, PostgreSQL, Paystack, Node.js',
      '   Link: https://masomo-net.vercel.app/',
      '',
      '3. Lishebora (Supported by Microsoft for Startups)',
      '   AI meal planner generating personalized plans based on health details',
      '   Technologies: Next.js, Tailwind CSS, Azure, Cosmos DB, OpenAI API',
      '   Link: http://lishebora.vercel.app/',
      '',
      '4. Charge24 Africa Payment Portal',
      '   Payment system for power bank dispensing machines serving 3,000+ customers',
      '   Technologies: Next.js, AWS S3, Amazon Lightsail, PostgreSQL, Daraja API',
      '   Link: https://charge24.africa/',
      '',
      'Type \'contact\' to discuss collaborations!',
    ],
  },
  {
    name: 'skills',
    description: 'My technical skills',
    response: [
      '💻 Technical Skills:',
      '',
      'Programming Languages:',
      '- JavaScript/TypeScript',
      '- Python',
      '- C#',
      '- C++',
      '',
      'Frontend:',
      '- React.js/Next.js',
      '- Redux/Zustand',
      '- Material UI',
      '- Tailwind CSS',
      '',
      'Backend:',
      '- Node.js/Express',
      '- Flask/FastAPI',
      '- .NET',
      '- SQL (PostgreSQL)',
      '- KQL (Kusto Query Language)',
      '',
      'Cloud & DevOps:',
      '- Azure',
      '- AWS',
      '- Docker/Kubernetes',
      '- Grafana & Prometheus',
      '- CI/CD Pipelines',
      '',
      'Machine Learning & Tools:',
      '- TensorFlow',
      '- Git/GitHub',
      '- Testing (Vitest, PyTest)',
      '- Bash Scripting',
    ],
  },
  {
    name: 'experience',
    description: 'My work experience',
    response: [
      '💼 Work Experience:',
      '',
      'Software Engineering Intern | Microsoft (July 2025 - Present)',
      '- Windows Team',
      '',
      'Microsoft Garage Intern | Microsoft (August 2024 - June 2025)',
      '- Developed inventory system with Azure OpenAI and RAG chatbot integration',
      '- Built file repository platform using Next.js and Azure cloud services',
      '- Contributed to Microsoft Global Hackathon with 87% registration rate',
      '- Facilitated 12 Game of Learners workshops for 200+ students',
      '',
      'Software Engineer | FarCas Consult – FCL (June 2024 - May 2025)',
      '- Leading Charge24 Africa\'s payment portal for 100+ power bank dispensing machines',
      '- Engineering membership portals for NextGen and Afrofit Gyms managing 700+ members',
      '- Implementing real-time data visualization for 500-1,000+ daily transactions',
      '- Setting up CI/CD pipelines that improved deployment speed by 60%',
      '',
      'Software Engineer | Digitalfarmer (Aug. 2023 - May 2024)',
      '- Collaborated with 4 developers on agricultural supply chain platform',
      '- Played key role in B2B/B2C platform that increased user base by 75%',
      '- Reduced load times by 20% through optimized front-end components',
      '',
      'Software Engineer | QuizardHQ (Apr. 2022 - July 2023)',
      '- Implemented frontend/backend with React.js, FastAPI, and AWS',
      '- Improved user engagement by 30% through system enhancements',
      '- Reduced user-reported issues by 25% through systematic troubleshooting',
      '',
      'Type \'projects\' to see my recent work.',
    ],
  },
  {
    name: 'contact',
    description: 'Contact information',
    response: [
      '📬 Get In Touch:',
      '',
      'Email: gateremg@gmail.com',
      'Phone: +254-757-826724',
      'GitHub: @gateremark [https://github.com/gateremark]',
      'LinkedIn: /in/gateremark [https://linkedin.com/in/gateremark]',
      'Twitter (X): @gatere_mark [https://x.com/gatere_mark]',
      '',
      'Feel free to reach out!',
    ],
  },
  {
    name: 'education',
    description: 'My educational background',
    response: [
      '🎓 Education:',
      '',
      'Bachelor\'s in Information Technology',
      '- Focused on software engineering, AI, and data structures',
      '- Relevant coursework: Algorithms, Database Systems, Computer Networks, AI/ML',
      '',
      'Additional Learning:',
      '- Continuous professional development through certifications',
      '- Self-guided study in cloud technologies and artificial intelligence',
      '- Regular participation in hackathons and coding challenges',
    ],
  },
  {
    name: 'certifications',
    description: 'My certifications',
    response: [
      '🏆 Certifications:',
      '',
      'Technical Certifications:',
      '- Microsoft Certified: Azure AI Fundamentals (Link)[https://learn.microsoft.com/en-us/users/gateremark/credentials/F865042F07E63125]',
      '- Andela: React Learning Program (Link)[https://credsverse.com/credentials/83b4903a-eadc-462c-b99f-12ac8dd171e1]',
      '- Data Analyst Associate Certificate - DataCamp (Link)[https://www.datacamp.com/certificate/DAA0017347104862]',
      '- SQL Associate Certificate - DataCamp (Link)[https://www.datacamp.com/certificate/SQA0011261438691]',
      '',
      'Industry Recognition:',
      '- Microsoft Global Hackathon Volunteer (Link)[https://www.credly.com/badges/728c91ad-61e0-45b3-b0bb-bf5105a93e4c/public_url]',
      '',
      'Visit my LinkedIn profile - \'contact\' - for a complete list of certifications.',
    ],
  },
  {
    name: 'leadership',
    description: 'Leadership and community involvement',
    response: [
      '👥 Leadership & Community:',
      '',
      'Speaking & Hosting:',
      '- Keynote Speaker - Enhance Mind AI Conference',
      '- Host - Global AI Conference, Student Edition',
      '- Featured Speaker - Microsoft Reactor',
      '',
      'Community Leadership:',
      '- Organizer - Google Developer Groups (GDG)',
      '- Lead - Google Developer Student Clubs',
      '- Beta - Microsoft Learn Student Ambassador',
      '',
      'Mentorship:',
      '- Technical workshop facilitator for Game of Learners (GOL) Clinics',
      '',
      'I\'m passionate about tech community building and knowledge sharing!',
    ],
  },
  {
    name: 'sudo',
    description: 'Run as administrator',
    response: 'Hi, I\'m Mark Gatere, a Software & AI Engineer.',
  },
  {
    name: 'clear',
    description: 'Clear terminal',
    response: 'CLEAR_TERMINAL',
  },
];